coverage:
  paths:
    - coverage.out
  badge:
    path: docs/coverage.svg
push:
codeToTestRatio:
  code:
    - '**/*.go'
    - '!**/*_test.go'
  test:
    - '**/*_test.go'
  badge:
    path: docs/ratio.svg
testExecutionTime:
  badge:
    path: docs/time.svg
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
report:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
body:
  if: is_pull_request
summary:
  if: true