name: Go test with report

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test-with-report:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read
      checks: write
      pull-requests: write

    env:
      GOTESTSUM_BIN: "${{ github.workspace }}/.tmp/gotestsum/bin"

    steps:
      - name: Print github.event_name
        run: echo "The event name is ${{ github.event_name }}"
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Cache gotestsum
        id: gotestsum-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.GOTESTSUM_BIN}}
          key: ${{ runner.os }}-go-gotestsum

      - name: Install gotestsum
        if: ${{ steps.gotestsum-cache.outputs.cache-hit != 'true' }}
        run: GOBIN="${{ env.GOTESTSUM_BIN }}" go install gotest.tools/gotestsum@latest

      - name: Run tests and generate JUnit report, test coverage
        run: "${{ env.GOTESTSUM_BIN }}/gotestsum --junitfile report.xml --format testdox --  -cover -coverprofile=coverage.out ./..."

      - name: Upload test report and coverage
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-report-and-coverage
          path: |
            report.xml
            coverage.out

      - name: Test Report Summary
        if: success() || failure()
        uses: dorny/test-reporter@v1
        with:
          name: Tests
          path: "*.xml"
          reporter: java-junit

      - uses: k1LoW/octocov-action@v1
